version: "3.4"

services:
  auth-service:
    image: node:10.6
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/micro-db-test
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
    command: /bin/sh -c "yarn install && yarn run dev"

  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
